ArticleBlog/ArticleBlog/urls.py
from django.contrib import admin
from django.urls import path,re_path
from Article.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
]
#博客路由部分
urlpatterns += [
    re_path('^$', index),
    path('index/', index),
    path('diary/', diary),
    path('myPhoto/', myPhoto),
    re_path('article_list/(?P<types>\w+)/',articleList),
    re_path('article_list/(?P<types>\w+)/(?P<page>\d+)/', articleList),
    re_path('articles/(?P<id>\d+)/', articles)
    # path('selfDiary/', selfDiary),
    # path('skillDiary/', skillDiary),
    # path('skillArticle/', skillArticle)
]

ArticleBlog/Article/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Article(models.Model):
    """
    文章类型：
        个人日记
        学习笔记
        技术文章
        个人简介
    文章族
        原创
        转载
    推荐
    """
    article_type = [
        ("selfDiary", "个人日记"),
        ("skillDiary", "学习笔记"),
        ("skillArticle", "技术文章"),
        ("diary", "个人简介"),
    ]
    article_family = [
        ("diary", "原创"),
        ("diary", "转载"),
    ]
    title = models.CharField(max_length = 32,verbose_name = "文章标题")
    author = models.CharField(max_length = 32,verbose_name = "文章作者")
    time = models.DateField(verbose_name = "发表时间")
    discription = RichTextField(verbose_name="文章描述")
    content = RichTextField(verbose_name="文章内容")
    picture = models.ImageField(verbose_name="文章图片", upload_to="images")
    favor = models.IntegerField(default = 0,verbose_name = "点赞数")
    articleType = models.CharField(max_length = 32,verbose_name = "文章类型",choices = article_type,default = "个人日记",)
    articleFamily = models.CharField(max_length = 32,verbose_name = "文章类型",choices = article_family,default = "原创",)
    recommend = models.BooleanField(verbose_name="推荐")


# Create your models here.

ArticleBlog/Article/views.py
from django.shortcuts import render
from django.core.paginator import Paginator

from Article.models import Article
# def Base(request):
#     """
#     模板页，默认不用视图指出，指出的目的是在创建之初进行调试使用
#     """
#     return render(request,"base.html")

def index(request):
    """
    首页
    """
    # 按照点赞数为主排序时间倒序为第二排序的逻辑查询所有推荐的文章
    articles = Article.objects.filter(recommend=True).order_by("favor", "-time")[:10]
    return render(request, "index.html",locals())


def diary(request):
    """
    个人简介
    展示推荐文章
    """
    title = "个人简介"
    article = Article.objects.get(id = 6)
    return render(request, "article.html", locals())

def myPhoto(request):
    """
    个人相册
    """
    return render(request, "my_photo.html")

def articleList(request,types,page=1):
    articleType = Article.article_type
    title, = [i[1] for i in articleType if i[0] == types]
    page = int(page)
    next_page = page+1
    last_page = page-1
    articles = Article.objects.filter(articleType=types).order_by("favor", "-time")
    paginator = Paginator(articles,8)
    data = paginator.page(page)
    return render(request,"article_list.html",locals())
def articles(request,id):
    article = Article.objects.get(id=id)
    try:
        previous_article = Article.objects.filter(id__lt=id)[0] #上一页
    except Exception as e:
        print(e)
    try:
        next_article = Article.objects.filter(id__gt=id)[0] #下一页
    except Exception as e:
        print(e)
    return render(request,"article.html",locals())
#
# def selfDiary(request):
#     """
#     个人日记
#     """
#     title = "个人日记"
#     articles = Article.objects.filter(recommend=True).order_by("favor", "-time")[:10]
#     return render(request, "article_list.html",locals())
#
# def skillDiary(request):
#     """
#     学习笔记
#     """
#     title = "学习笔记"
#     return render(request, "article_list.html",locals())
#
# def skillArticle(request):
#     """
#     技术文章
#     """
#     title = "技术文章"
#     return render(request, "article_list.html",locals())

def message(request):
    """
    给我留言
    """
    return render(request, "tem/index.html")

# Create your views here.

ArticleBlog/templates/article.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block style %}
    <link href="/static/css/main.css" rel="stylesheet">
{% endblock %}

{% block content %}
      <div class="container">
    <div class="con_content">
      <div class="about_box">
        <h2 class="nh1"><span>您现在的位置是：<a href="/" target="_blank">网站首页</a>>><a href="#" target="_blank">信息浏览</a></span><b>个人简介</b></h2>
        <div class="f_box">
          <p class="a_title">{{ article.title }}</p>
          <p class="p_title"></p>
          <!--  <p class="box_p"><span>发布时间：2017-07-07 15:12:42</span><span>作者：唐孝文</span><span>来源：稽查支队</span><span>点击：111056</span></p>-->
          <!-- 可用于内容模板 -->
        </div>
        <ul class="about_content">
          {{ article.content|safe }}
        </ul>
        {% ifequal article.articleType "diary" %}
        {% else %}
        <div class="nextinfos">
            <p>上一篇：<a href="/articles/{{ previous_article.id }}/">{{ previous_article.title }}</a></p>
            <p>下一篇：<a href="/articles/{{ next_article.id }}/">{{ next_article.title }}</a></p>
        </div>
        {% endifequal %}
        <!-- 可用于内容模板 -->

        <!-- container代码 结束 -->
      </div>
    </div>
    <div class="blank"></div>
  </div>
{% endblock %}

ArticleBlog/templates/article_list.html
{% extends "base.html" %}

{% block title %}
    文章列表页
{% endblock %}

{% block style %}
    <link href="/static/css/main.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
  <div class="con_content">
    <div class="about_box">
      <h2 class="nh1"><span>您现在的位置是：<a href="/" target="_blank">网站首页</a>>><a href="#" target="_blank">个人日记</a></span><b>{{ title }}</b></h2>
      <div class="dtxw box">
        {% for article in data %}
            <li>
          <div class="dttext f_l">
            <ul>
              <h2><a href="/articles/{{ article.id }}/">{{ article.title }}</a></h2>
              <p>{{ article.discription|safe }}</p>
              <span>{{ article.time }}</span>
            </ul>
          </div>
          <div class="xwpic f_r"><a href="/"><img src="/static/images/{{ article.picture }}"></a></div>
        </li>
        {% endfor %}
      </div>
      <div class="pagelist">页次：{{ page }}/{{ paginator.num_pages }} 每页8 总数{{ paginator.count }}<a href="/article_list/{{ types }}/">首页</a><a href="/article_list/{{ types }}/{{ last_page }}/">上一页</a><a href="/article_list/{{ types }}/{{ next_page }}/">下一页</a><a href="/">尾页</a></div>
    </div>
  </div>
  <div class="blank"></div>
  <!-- container代码 结束 -->

  <footer>
    <div class="footer">
      <div class="f_l">
        <p>All Rights Reserved 版权所有：<a href="http://www.yangqq.com">杨青个人博客</a> 备案号：蜀ICP备00000000号</p>
      </div>
      <div class="f_r textr">
        <p>Design by DanceSmile</p>
      </div>
    </div>
  </footer>
</div>
{% endblock %}

ArticleBlog/templates/base.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>
    {% block tiltle %}
        边进辉-个人博客
    {% endblock %}
</title>
<meta name="keywords" content="边进辉-个人博客" />
<meta name="description" content="边进辉-个人博客" />
<link href="/static/css/base.css" rel="stylesheet">
<link href="/static/css/index.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="/static/js/modernizr.js"></script>
<![endif]-->
<script type="text/javascript" src="/static/js/jquery.js"></script>
{% block style %}
{% endblock %}
</head>
<body>

<div id="wrapper">
  <header>
    <div class="headtop"></div>
    <div class="contenttop">
      <div class="logo f_l">
          {% if title %}
            {{ title }}
          {% else %}
            边进辉-个人博客
          {% endif %}
      </div>
      <div class="search f_r">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="blank"></div>
      <nav>
        <div  class="navigation">
          <ul class="menu">
            <li><a href="/index/">网站首页</a></li>
            <li><a href="/diary/">关于我</a>
              <ul>
                <li><a href="/diary/">个人简介</a></li>
                <li><a href="/myPhoto/">个人相册</a></li>
              </ul>
            </li>
            <li><a href="/article_list/selfDiary/">我的日记</a>
              <ul>
                <li><a href="/article_list/selfDiary/">个人日记</a></li>
                <li><a href="/article_list/skillDiary/">学习笔记</a></li>
              </ul>
            </li>
            <li><a href="/article_list/skillArticle/">技术文章</a> </li>
            <li><a href="#">给我留言</a> </li>
          </ul>
        </div>
      </nav>
      <SCRIPT type=text/javascript>
	// Navigation Menu
	$(function() {
		$(".menu ul").css({display: "none"}); // Opera Fix
		$(".menu li").hover(function(){
			$(this).find('ul:first').css({visibility: "visible",display: "none"}).slideDown("normal");
		},function(){
			$(this).find('ul:first').css({visibility: "hidden"});
		});
	});
</SCRIPT> 
    </div>
  </header>
  {% block content %}
  {% endblock %}
  <footer>
    <div class="footer">
{#      <div class="f_l">#}
{#        <p>All Rights Reserved 版权所有：<a href="http://www.yangqq.com">杨青个人博客</a> 备案号：蜀ICP备00000000号</p>#}
{#      </div>#}
      <div class="f_r textr">
        <p>Design by DanceSmile</p>
      </div>
    </div>
  </footer>
</div>
{% block script %}
{% endblock %}
</body>
</html>

ArticleBlog/templates/diary.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block style %}
    <link href="/static/css/main.css" rel="stylesheet">
{% endblock %}

{% block content %}
      <div class="container">
    <div class="con_content">
      <div class="about_box">
        <h2 class="nh1"><span>您现在的位置是：<a href="/" target="_blank">网站首页</a>>><a href="#" target="_blank">信息浏览</a></span><b>个人简介</b></h2>
        <div class="f_box">
          <p class="a_title">个人简介</p>
          <p class="p_title"></p>
          <!--  <p class="box_p"><span>发布时间：2017-07-07 15:12:42</span><span>作者：唐孝文</span><span>来源：稽查支队</span><span>点击：111056</span></p>-->
          <!-- 可用于内容模板 -->
        </div>
        <ul class="about_content">
          <p> 人生就是一个得与失的过程，而我却是一个幸运者，得到的永远比失去的多。生活的压力迫使我放弃了轻松的前台接待，放弃了体面的编辑，换来虽有些蓬头垢面的工作，但是我仍然很享受那些熬得只剩下黑眼圈的日子，因为我在学习使用Photoshop、Flash、Dreamweaver、ASP、PHP、JSP...中激发了兴趣，然后越走越远....</p>
          <p><img src="/static/images/01.jpg"></p>
          <p>“冥冥中该来则来，无处可逃”。 </p>
        </ul>
        <div class="nextinfos">
            <p>上一篇：<a href="/">区中医医院开展志愿服务活动</a></p>
            <p>下一篇：<a href="/">广安区批准“单独两孩”500例</a></p>
        </div>
        <!-- 可用于内容模板 -->

        <!-- container代码 结束 -->
      </div>
    </div>
    <div class="blank"></div>
  </div>
{% endblock %}

ArticleBlog/templates/index.html
{% extends 'base.html' %}

{% block tiltle %}
    边进辉个人博客-首页
{% endblock %}

{% block content %}
  <div class="jztop"></div>
  <div class="container">
    <div class="bloglist f_l">
      {% for article in articles %}
      <h3><a href="/jstt/bj/2017-07-13/784.html">【{{ article.get_articleType_display }}】{{ article.title }}</a></h3>
      <figure><img src="/static/images/{{ article.picture }}" alt="【{{ article.get_articleType_display }}】{{ article.title }}"></figure>
      <ul>
        <p> {{ article.discription|safe }}</p>
        <a title="【{{ article.get_articleType_display }}】{{ article.title }}" href="/jstt/bj/2017-07-13/784.html" target="_blank" class="readmore">阅读全文&gt;&gt;</a>
      </ul>
      <p class="dateview"><span>{{ article.time }}</span><span>作者：{{ article.author }}</span><span>个人博客：[<a href="/jstt/bj/">{{ article.get_articleType_display }}</a>]</span></p>
      {% endfor %}
    </div>
    <div class="r_box f_r">
      <div class="tit01">
        <h3 class="tit">关注我</h3>
        <div class="gzwm">
          <ul>
            <li><a class="email" href="#" target="_blank">我的电话</a></li>
            <li><a class="qq" href="#mailto:admin@admin.com" target="_blank">我的邮箱</a></li>
            <li><a class="tel" href="#" target="_blank">我的QQ</a></li>
            <li><a class="prize" href="#">个人奖项</a></li>
          </ul>
        </div>
      </div>
      <!--tit01 end-->
      
      <div class="tuwen">
        <h3 class="tit">图文推荐</h3>
        <ul>
          {% for article in articles %}
          <li><a href="/"><img src="/static/images/{{ article.picture }}"><b>{{ article.title }}</b></a>
            <p><span class="tulanmu"><a href="/">{{ article.get_articleType_display }}</a></span><span class="tutime">{{ article.time }}</span></p>
          </li>
          {% endfor %}
        </ul>
      </div>
      <div class="ph">
        <h3 class="tit">点击排行</h3>
        <ul class="rank">
            {% for article in articles %}
              <li><a href="/articles/{{ article.id }}/" title="【{{ article.get_articleFamily_display }}】{{ article.title }}" target="_blank">【{{ article.get_articleFamily_display }}】{{ article.title }}</a></li>
            {% endfor %}
        </ul>
      </div>
      <div class="ad"> <img src="/static/images/03.jpg"> </div>
    </div>
  </div>
  <!-- container代码 结束 -->
  <div class="jzend"></div>
{% endblock %}

ArticleBlog/templates/my_photo.html
{% extends "base.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block style %}
    <link href="/static/css/main.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
  <div class="con_content">
    <div class="about_box">
      <h2 class="nh1"><span>您现在的位置是：<a href="/" target="_blank">网站首页</a>>><a href="#" target="_blank">个人相册</a></span><b>个人相册</b></h2>
      <div class="lispic">
        <ul>
          <li><a href="/"><img src="/static/images/01.jpg"><span>图片展示</span></a></li>
          <li><a href="/"><img src="/static/images/02.jpg"><span>图片展示</span></a></li>
          <li><a href="/"><img src="/static/images/03.jpg"><span>图片展示</span></a></li>
          <li><a href="/"><img src="/static/images/04.jpg"><span>图片展示</span></a></li>
          <li><a href="/"><img src="/static/images/03.jpg"><span>图片展示</span></a></li>
          <li><a href="/"><img src="/static/images/06.jpg"><span>图片展示</span></a></li>
          <li><a href="/"><img src="/static/images/01.jpg"><span>图片展示</span></a></li>
          <li><a href="/"><img src="/static/images/02.jpg"><span>图片展示</span></a></li>
        </ul>
      </div>
      <div class="pagelist">页次：1/1 每页25 总数10<a href="/">首页</a><a href="/">上一页</a><a href="/">下一页</a><a href="/">尾页</a></div>
    </div>
  </div>
  <div class="blank"></div>
  <!-- container代码 结束 -->
  
  <footer>
    <div class="footer">
      <div class="f_l">
        <p>All Rights Reserved 版权所有：<a href="http://www.yangqq.com">杨青个人博客</a> 备案号：蜀ICP备00000000号</p>
      </div>
      <div class="f_r textr">
        <p>Design by DanceSmile</p>
      </div>
    </div>
  </footer>
</div>
{% endblock %}

ArticleBlog/templates/tem/newslistpic.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>个人博客模板古典系列之――江南墨卷</title>
<meta name="keywords" content="个人博客模板古典系列之――江南墨卷" />
<meta name="description" content="个人博客模板古典系列之――江南墨卷" />
<link href="/static/css/base.css" rel="stylesheet">
<link href="/static/css/main.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="/static/js/modernizr.js"></script>
<![endif]-->
<script type="text/javascript" src="/static/js/jquery.js"></script>
</head>
<body>
<div id="wrapper">
<header>
  <div class="headtop"></div>
  <div class="contenttop">
    <div class="logo f_l">个人博客模板古典系列之――江南墨卷</div>
    <div class="search f_r">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="blank"></div>
    <nav>
      <div  class="navigation">
        <ul class="menu">
          <li><a href="index.html">网站首页</a></li>
          <li><a href="#">关于我</a>
            <ul>
              <li><a href="about.html">个人简介</a></li>
              <li><a href="listpic.html">个人相册</a></li>
            </ul>
          </li>
          <li><a href="#">我的日记</a>
            <ul>
              <li><a href="newslistpic.html">个人日记</a></li>
              <li><a href="newslistpic.html">学习笔记</a></li>
            </ul>
          </li>
          <li><a href="newslistpic.html">技术文章</a> </li>
          <li><a href="#">给我留言</a> </li>
        </ul>
      </div>
    </nav>
    <SCRIPT type=text/javascript>
	// Navigation Menu
	$(function() {
		$(".menu ul").css({display: "none"}); // Opera Fix
		$(".menu li").hover(function(){
			$(this).find('ul:first').css({visibility: "visible",display: "none"}).slideDown("normal");
		},function(){
			$(this).find('ul:first').css({visibility: "hidden"});
		});
	});
</SCRIPT> 
  </div>
</header>
<div class="container">
  <div class="con_content">
    <div class="about_box">
      <h2 class="nh1"><span>您现在的位置是：<a href="/" target="_blank">网站首页</a>>><a href="#" target="_blank">个人日记</a></span><b>个人日记</b></h2>
      <div class="dtxw box">
        <li>
          <div class="dttext f_l">
            <ul>
              <h2><a href="/">个人博客模板古典系列之――江南墨卷</a></h2>
              <p>个人博客模板古典系列之――江南墨卷个人博客模板古典系列之――江南墨卷个人博客模板古典系列之――江南墨卷原汁原味重现经典....</p>
              <span>2017-3-10</span>
            </ul>
          </div>
          <div class="xwpic f_r"><a href="/"><img src="/static/images/02.jpg"></a></div>
        </li>
        <li>
          <div class="dttext f_l">
            <ul>
              <h2><a href="/">个人博客模板古典系列之――江南墨卷</a></h2>
              <p>个人博客模板古典系列之――江南墨卷个人博客模板古典系列之――江南墨卷广安领先....</p>
              <span>2017-3-10</span>
            </ul>
          </div>
          <div class="xwpic f_r"><a href="/"><img src="/static/images/01.jpg"></a></div>
        </li>
        <li>
          <div class="dttext f_l">
            <ul>
              <h2><a href="/">个人博客模板古典系列之――江南墨卷</a></h2>
              <p>个人博客模板古典系列之――江南墨卷个人博客模板古典系列之――江南墨卷个人博客模板古典系列之――江南墨卷原汁原味重现经典....</p>
              <span>2017-3-10</span>
            </ul>
          </div>
          <div class="xwpic f_r"><a href="/"><img src="/static/images/03.jpg"></a></div>
        </li>
        <li>
          <div class="dttext f_l">
            <ul>
              <h2><a href="/">个人博客模板古典系列之――江南墨卷</a></h2>
              <p>个人博客模板古典系列之――江南墨卷个人博客模板古典系列之――江南墨卷个人博客模板古典系列之――江南墨卷原汁原味重现经典</p>
              <span>2017-3-10</span>
            </ul>
          </div>
          <div class="xwpic f_r"><a href="/"><img src="/static/images/04.jpg"></a></div>
        </li>
        <li>
          <div class="dttext f_l">
            <ul>
              <h2><a href="/">个人博客模板古典系列之――江南墨卷</a></h2>
              <p>个人博客模板古典系列之――江南墨卷个人博客模板古典系列之――江南墨卷个人博客模板古典系列之――江南墨卷原汁原味重现经典</p>
              <span>2017-3-10</span>
            </ul>
          </div>
          <div class="xwpic f_r"><a href="/"><img src="/static/images/02.jpg"></a></div>
        </li>
        <li>
          <div class="dttext f_l">
            <ul>
              <h2><a href="/">个人博客模板古典系列之――江南墨卷</a></h2>
              <p>个人博客模板古典系列之――江南墨卷个人博客模板古典系列之――江南墨卷个人博客模板古典系列之――江南墨卷原汁原味重现经典</p>
              <span>2017-3-10</span>
            </ul>
          </div>
          <div class="xwpic f_r"><a href="/"><img src="/static/images/06.jpg"></a></div>
        </li>
      </div>
      <div class="pagelist">页次：1/1 每页25 总数10<a href="/">首页</a><a href="/">上一页</a><a href="/">下一页</a><a href="/">尾页</a></div>
    </div>
  </div>
  <div class="blank"></div>
  <!-- container代码 结束 -->
  
  <footer>
    <div class="footer">
      <div class="f_l">
        <p>All Rights Reserved 版权所有：<a href="http://www.yangqq.com">杨青个人博客</a> 备案号：蜀ICP备00000000号</p>
      </div>
      <div class="f_r textr">
        <p>Design by DanceSmile</p>
      </div>
    </div>
  </footer>
</div>
</body>
</html>